package cn;

import java.util.Scanner;

public class CRCDemo {
static Scanner scan = new Scanner(System.in);
	
	public static void main(String args[]) {
		int i;
		int[] msgtx, div, msgrx;
		int n;
		CRC c = new CRC();
		System.out.println("Enter the size of the Message:");
		n = scan.nextInt();
		msgtx = readArray(n);
		c.setMessage(msgtx);
	
		System.out.println("Enter the size of the Divisor:");
		n = scan.nextInt();
		div = readArray(n);
		c.setDivisor(div);
		
		// Divide the data by the divisor given
		// Store the remainder that is returned by the method
		int remainder[] = c.crcDivide();
				
		System.out.println("The Remainder is......");
		for( i=0 ; i < remainder.length-1 ; i++) {
			System.out.print(remainder[i]);
		}
		
		System.out.println("\nThe CRC code generated is:");
		printArray(msgtx);
		printRem(remainder);
		
		System.out.println();
		
		// Create a new array. 
		//It will have the remainder generated by the above method appended
		// to the input data
		msgrx = new int[c.getMessage().length + remainder.length - 1];
		
		System.out.println("Enter the data to be sent:");
		msgrx = readArray(c.getMessage().length + remainder.length - 1);
			
		c.setMessage(msgrx);
		c.crcReceive();
		scan.close();
	}
	
	static int[] readArray(int n) {
		int i;
		int data[] = new int[n];
		System.out.println("Enter the data, bit by bit:");
		for( i=0 ; i < n ; i++) {
			System.out.println("Enter bit number " + (n-i) + ":");
			data[i] = scan.nextInt();
		}
		return data;
	}
	
	static void printArray(int[] arraytoprint) {
		int i;
		for( i=0 ; i < arraytoprint.length ; i++) {
			System.out.print(arraytoprint[i]);
		}	
	}
	
	static void printRem(int[] arraytoprint) {
		int i;
		for( i=0 ; i < arraytoprint.length - 1 ; i++) {
			System.out.print(arraytoprint[i]);
		}	
	}
	
}
